version: 2.1

# ------------
#     Orbs
# ------------

orbs:
    git-shallow-clone: guitarrapc/git-shallow-clone@2.8.0

# ------------
#   Anchors
# ------------

variables:
  working_directory: &working_directory /mnt/ramdisk/prism-design-system

defaults: &defaults
  working_directory: *working_directory

attach_workspace: &attach_workspace
  attach_workspace:
    at: *working_directory

dev: &dev
  filters:
    branches:
      ignore:
      - main

# -------------
#   Executors
# -------------

executors:
  node:
    <<: *defaults
    docker:
    - image: cimg/node:18.16.0

# ------------
#   Commands
# ------------

commands:
  setup_artifactory:
    description: 'Set up Artifactory config'
    steps:
    - run:
        name: Set up Artifactory
        command: |
          echo "Configuring npm client for @pendo Artifactory packages..."
          if [ -z "$ARTIFACTORY_TOKEN" ]; then
            echo "ARTIFACTORY_TOKEN NOT SET" && exit 1;
          else
            echo "@pendo:registry=https://pendo.jfrog.io/artifactory/api/npm/web/" > ~/.npmrc;
            echo "//pendo.jfrog.io/artifactory/api/npm/web/:_authToken=${ARTIFACTORY_TOKEN}" >> ~/.npmrc
            echo "//pendo.jfrog.io/artifactory/api/npm/web/:email=team-ops@pendo.io" >> ~/.npmrc
            echo "//pendo.jfrog.io/artifactory/api/npm/web/:always-auth=true" >> ~/.npmrc
            echo "npm client configured successfully!";
          fi

# ------------
#     Jobs
# ------------

jobs:
  setup:
    executor: node
    steps:
    - git-shallow-clone/checkout
    - restore_cache:
        keys:
        - dependencies-{{ arch }}-v1-{{ checksum "package-lock.json" }}
        - dependencies-{{ arch }}-v1-
    - setup_artifactory
    - run:
        name: Install dependencies
        command: npm ci
    - save_cache:
        key: dependencies-{{ arch }}-v1-{{ checksum "package-lock.json" }}
        paths:
        - ~/.npm
    - persist_to_workspace:
        root: *working_directory
        paths:
          - .

  build:
    executor: node
    steps:
    - <<: *attach_workspace
    - run:
        name: build
        command: npm run build
    - persist_to_workspace:
        root: *working_directory
        paths:
          - dist


  deploy-lookaside-gcs:
    executor: node
    steps:
    - <<: *attach_workspace
    - run:
        name: prepare gcloud credentials
        command: |
          echo $GCLOUD_SERVICE_KEY > "gcloud-service-key.json"
    - run:
        name: deploy
        command: node scripts/lookaside.mjs --keyFilename=gcloud-service-key.json --branch ${CIRCLE_BRANCH}

# -------------
#   Workflows
# -------------

workflows:
  dev:
    jobs:
    - setup:
        name: setup
        context:
        - artifactory-web
    - build:
        name: build
        requires:
        - setup
    - deploy-lookaside-gcs:
        <<: *dev
        name: deploy-lookaside-gcs
        context:
        - core-dev
        requires:
        - setup
        - build

